# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.klusterletAddonController.name }}-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.klusterletAddonController.name }}-v2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.klusterletAddonController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.klusterletAddonController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  minReadySeconds: 0
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.klusterletAddonController.name }}-v2
      component: {{ .Values.klusterletAddonController.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.klusterletAddonController.name }}-v2
        ocm-antiaffinity-selector: "klusterletaddon"
        component: {{ .Values.klusterletAddonController.name }}
        release: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.klusterletAddonController.name }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      serviceAccountName: {{ .Values.klusterletAddonController.name }}-v2
      hostNetwork: false
      hostPID: false
      hostIPC: false
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
      {{- with .Values.klusterletAddonControllerAffinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubconfig.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: klusterlet-addon-controller
        image: "{{ .Values.global.imageOverrides.klusterlet_addon_controller }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
        {{- toYaml .Values.klusterletAddonController.resources | nindent 10 }}
        env:
          - name: WATCH_NAMESPACE
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ .Values.klusterletAddonController.name }}
          - name: USE_SHA_MANIFEST
            value: "{{ .Values.global.useShaManifest }}"
          - name: DEFAULT_IMAGE_PULL_SECRET
            value: {{ .Values.global.imagePullSecret }}
          - name: DEFAULT_IMAGE_REGISTRY
            value: {{ .Values.global.imageRepository }}
          - name: ADDON_CLUSTERROLE_PREFIX
            value: "{{ .Values.org }}:{{ .Release.Name }}:addons:"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
