# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:search-api
rules:
- apiGroups: ["console.open-cluster-management.io"]
  resources: ["userpreferences"]
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups: [""]
  resources: ["namespaces"]
  verbs:
  - list
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs:
  - list
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs:
  - create
- apiGroups: ["search.open-cluster-management.io"]
  resources: ["searchoperators"]
  verbs:
  - get
