# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.org }}:{{ .Release.Name }}:search-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - helmreleases
  verbs:
  - get
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch   
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
    - authorization.k8s.io
  resources:
    - subjectaccessreviews
  verbs:
    - get
    - create
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests
    - certificatesigningrequests/approval
  verbs:
    - get
    - list
    - watch
    - create
    - update
- apiGroups:
    - certificates.k8s.io
  resources:
    - signers
  verbs:
    - approve
- apiGroups:
    - cluster.open-cluster-management.io
  resources:
    - managedclusters
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - work.open-cluster-management.io
  resources:
    - manifestworks
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - deletecollection
    - patch
- apiGroups:
    - addon.open-cluster-management.io
  resources:
    - managedclusteraddons
    - clustermanagementaddons
    - managedclusteraddons/finalizers
    - clustermanagementaddons/finalizers
    - managedclusteraddons/status
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiGroups:
    - proxy.open-cluster-management.io
  resources:
    - clusterstatuses/aggregator
  verbs:
    - create
